### ISSUE TITLE
Empty Whitespace in installer.php

### ISSUE THREAD

**Issue by Harrison-B** [lifeinthegrid/duplicator#166]
I'm a fairly newbie PHP dev, however I noticed an issue that broke my migration using Duplicator several times. Basically, I was migrating a fairly large site with a large amount of plugins that kept causing issues (Revolution Slider in particular). But besides from that, after I had made my package and uploaded, installer.php would run but when it switched to main-installer it gave me a very generic error and an option to restart the install which did not help. 

The error was about erroneous headings located on line 67 of the installer.php (something about cookies if I recall).

Deleting the 7 empty lines at the start of installer.php allowed it to be run correctly, and disabling all plugins in step 3 or 4 allowed me to successfully get into the backend and get setup. Don't know if this is an actual issue or bug in Duplicator or an error specific to my setup. 

Another thing to note is that the "wp-content" folder was names "content" in the last installation, so this has caused a few issues that I have temporarily solved by just duplicating the folder and renaming it "content" so that no images fail to load. Does Duplicator automatically convert URLs and references to a renamed wp-content folder?

**Comment by lifeinthegrid** [comment]
Hey Harrison-B,

Thanks for the feedback.  With PHP it's tough to know is some cases since the servers can be configured with so many options. If you want to submit a <a href='https://snapcreek.com/ticket'>support ticket</a> for this issue I can have a closer look at your setup.  Please provide a link to this thread when submitting the ticket.

To your last question, on step 3 of the installer Duplicator does try to replace all the old urls with your new url and also and server paths that you have.

Thanks~
