### ISSUE TITLE
Duplicator MySQL queries not compatible with default DigitalOcean Wordpress image environment, among many others

### ISSUE THREAD

**Issue by chuckhacker** [lifeinthegrid/duplicator#19]
Due to MySQL compatibility hell, I had to manually add `SET SESSION sql_mode='NO_ENGINE_SUBSTITUTION';` to my installer archive's `database.sql` file to get this to work. It was VERY non-obvious and took quite some time for me to figure out.

```
# mysql --version
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
```

There needs to be a better way to prevent new users from snagging on this -- this is a very common issue; there are all sorts of support forum posts with this issue everywhere on the Internet.

Would you ever consider adding that line to the file yourself out-of-the-box? Or at least providing better instructions in the Step 3 Test "Issues" section where you do provide similarly-detailed issue resolution instructions (but none for this specific workaround)?

**Comment by lifeinthegrid** [comment]
Hi Chuck,

Totally agree... We are currently working to improve this workflow.   There is an option in the Advanced Section of the installer for entering the SQL Mode, however we are working on some pre-integrity checkers to help users spot these issues more easily.  It will probably be over the next several releases that we will start to introduce some of these features in basic formats, this issue is definitely on the radar, but will take some time to iron out...

Thanks for the feedback!

**Comment by chuckhacker** [comment]
Thanks a bunch @lifeinthegrid !
